### PR TITLE
Solved  Internet connectivity check methods #19

### PR DESCRIPTION
**Pull request by gouri-panda**
- Added internet check methods across the app. If the internet connection isn't or the internet goes suddenly while loading, display a  Snack bar showing No Internet connection after 15 sec.

### CODE REVIEW

**Comment by gouri-panda** [comment]
@sonusourav Please review it and merge it.

**Review by sonusourav — CHANGES_REQUESTED** [review]
Hey, could you add a description in your PR, what changes have you made?
P.S.: I was unwell for the last few days so was not able to review your PR.

**Comment by gouri-panda** [comment]
Hey, @sonusourav  I didn't understand , where should I add description  in my Repo or  Here?

**Comment by sonusourav** [comment]
Description here like what changes have you made. I meant what difference is there before and after your PR.

**Comment by gouri-panda** [comment]
@sonusourav  Done.

**Comment by sonusourav** [comment]
Hey, first why should it be displayed after 15 sec why not instantly as other apps do.
Second, it's not displaying the Snackbar even after 15 sec 😅 

internet

**Comment by gouri-panda** [comment]
> Hey, first why should it be displayed after 15 sec why not instantly as other apps do.
> Second, it's not displaying the Snackbar even after 15 sec 😅

No, if the app hasn't internet connection it will instantly display it.also if the internet connection goes suddenly while progress bar loading then it displays after 15 sec as you said in the issue section.

**Comment by gouri-panda** [comment]
@sonusourav  I am sorry i only added where progress dialog appears.

**Comment by sonusourav** [comment]
> 
> 
> @sonusourav I am sorry i only added where progress dialog appears.

No issues. The PR is in accordance with the issue

**Comment by gouri-panda** [comment]
Thank you for accepting my PR @sonusourav .

**Pull request merged**
