### PR TITLE
Settings theme issue fixed

### LINKED ISSUE #5: Settings theme does not match with app's theme
**Describe the bug**
White text is used over black background in Settings while its opposite in other screens of the app

**To Reproduce**
1. Go to Settings screen
2. Observe the difference

**Expected behavior**
Black text should be used in white background.

**Screenshots**
settings_theme

**Smartphone (please complete the following information):**
 - Device: Redmi 4
 - OS: Android Nougat

### PR DESCRIPTION
**Pull request by rob729**
Fixes #5 
Screenshot_2019-07-01-11-04-00-446_com iitdh sonusourav instigo

### CODE REVIEW

**Comment by rob729** [comment]
@sonusourav Please review this PR.

**Comment by sonusourav** [comment]
Please squash your commits into one.

**Comment by rob729** [comment]
I tried to squash my commits into one but it got messed up.
I have recently closed a PR in which I tried to squash all the commits into one.
Can you have a look at it? #26

**Comment by sonusourav** [comment]
> 
> 
> I tried to squash my commits into one but it got messed up.
> I have recently closed a PR in which I tried to squash all the commits into one.
> Can you have a look at it? #26

Come to gitter

**Comment by sonusourav** [comment]
@rob729 The chemistry between the switch and the background is still not good. Instead, try to change the style of the switch ( off color). And use a bit darker color for the text ( instead of hint color).

**Comment by rob729** [comment]
@sonusourav I am working on this issue.
Till then can you have a look at PR #27.

**Pull request closed without merging**
